//created Mar 01, 2023 - 22:57:21
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.utils.Calculator;
import it.cnr.isti.labsedc.concern.notification.NotificationManager;

//Monitor the quotation received from brokers

dialect "java"

declare ConcernBaseEvent
    @role( event )
    @timestamp( timestamp )
    @expires(90s)
end

rule "Monitoring the quotation received from brokers"
no-loop
salience 10
dialect "java"
when 

not (Number( longValue > 10 ) from accumulate(
	        $evt : ConcernBaseEvent(name == "QuotationFromBroker", senderID == "SevenBullsSimProbe" ) over window:time( 60s ),
	        count(1)));
    then
	NotificationManager.NotifyViolation("SevenBullsSimProbe", "Warning - actually system does not received more than 10 quotation per minute - Rule fired:" + drools.getRule().getName(), drools.getRule().getName(), drools.getRule().getMetaData());
end