//created Feb 17, 2023 - 16:55:32
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.utils.Calculator;
import it.cnr.isti.labsedc.concern.notification.NotificationManager;

//Check a sequence of events strictly

dialect "java"

declare ConcernBaseEvent
    @role( event )
    @timestamp( timestamp )
    @expires(2m)
end

rule "observe errors in timeframe"
no-loop
salience 10
dialect "java"
when 

Number( longValue > 1 ) from accumulate(
	        ConcernBaseEvent(name == "ERROR_NAME", senderID == "SevenBullsErrorSimProbe" ) over window:time( 60s ),
	        count(1) )   	 		
    then
	NotificationManager.NotifyToConsumer("SevenBullsErrorSimProbe", "Error - More than one failure event in timeframe event - Rule fired:" + drools.getRule().getName());	
end