//created on: Mar 18, 2022
package it.cnr.isti.labsedc.concern.event;

import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.notification.NotificationManager;

dialect "java"

declare ConcernAbstractEvent
    @role( event )
    @timestamp( timestamp )
end


rule "check that only one connection is active"
no-loop
salience 10
dialect "java" 
	when
		$aEvent : ConcernBaseEvent(
		this.getName == "Connection",
		this.getSenderID == "SUA_probe",
		this.getDestinationID == "Monitoring",
		this.getData == "established");
		
		$bEvent : ConcernBaseEvent(
		this.getName == "Connection",
		this.getSenderID == "SUA_probe",
		this.getDestinationID == "Monitoring",
		this.getData == "established",
		this after $aEvent)				
		not(ConcernBaseEvent(
			this.getName == "Connection",		
			this.getSenderID == "SUA_probe",
			this.getDestinationID == "Monitoring",
			this.getData == "closed",
			this after $aEvent));
		
		//this not meets [2s] $aEvent);
	then
		KieLauncher.printWarning("More than one connection between LocalPlanner and Global Planner established. Shut down systems");	
		retract($aEvent);
		retract($bEvent);	
end