//created Jan 24, 2023 - 17:41:32
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.event.ConcernICTGatewayEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.utils.Calculator;

//Check a sequence of events strictly

dialect "java"

declare ConcernICTGatewayEvent
    @role( event )
    @timestamp( timestamp )
    @expires (24h)
end

declare FirstAndSecondEvent
    @role( event )
	first : ConcernICTGatewayEvent
	second: ConcernICTGatewayEvent
end

rule "catchFirstAndSecond"
no-loop
salience 10
dialect "java"
when
	$aEvent: ConcernICTGatewayEvent(
		this.senderID == "ICTGW_Probe",
		this.destinationID == "Monitoring",
		this.name == "AUTHENTICATION_REQUEST",
		this.ICTMessageType == "AUTHENTICATION_REQUEST",
		this.ICTMessageCategory == "AUTHENTICATION"
		);
		
	$bEvent: ConcernICTGatewayEvent(
		this.senderID == $aEvent.getSenderID,
		this.destinationID == $aEvent.getDestinationID,
		this.name == "REGISTRATION_RESPONSE",
		this.ICTMessageType == "REGISTRATION_RESPONSE",
		this.ICTMessageCategory == "REGISTRATION",
		this after $aEvent);
	
then
	FirstAndSecondEvent captured = new FirstAndSecondEvent();
	captured.setFirst($aEvent);
	captured.setSecond($bEvent);
	insert(captured);
	retract($aEvent);
	retract($bEvent);
end